agencies:
  abc:
    url: https://www.gov.br/abc/pt-br/assuntos/noticias
    active: true
  abcd:
    url: https://www.gov.br/abcd/pt-br/noticias
    active: true
  abin:
    url: https://www.gov.br/abin/pt-br/centrais-de-conteudo/noticias
    active: true
  acessoainformacao:
    url: https://www.gov.br/acessoainformacao/pt-br/noticias
    active: true
  aeb:
    url: https://www.gov.br/aeb/pt-br/assuntos/noticias
    active: true
  agricultura:
    url: https://www.gov.br/agricultura/pt-br/assuntos/noticias
    active: true
  agu:
    url: https://www.gov.br/agu/pt-br/comunicacao/noticias
    active: true
  aids:
    url: https://www.gov.br/aids/pt-br/assuntos/noticias
    active: true
  ana:
    url: https://www.gov.br/ana/pt-br/assuntos/noticias-e-eventos/noticias
    active: true
  anac:
    url: https://www.gov.br/anac/pt-br/noticias/ultimas-noticias-1
    active: true
  anatel:
    url: https://www.gov.br/anatel/pt-br/assuntos/noticias
    active: true
  ancine:
    url: https://www.gov.br/ancine/pt-br/assuntos/noticias
    active: true
  aneel:
    url: https://www.gov.br/aneel/pt-br/assuntos/noticias
    active: true
  anm:
    url: https://www.gov.br/anm/pt-br/assuntos/noticias/ultimas-noticias
    active: true
  anp:
    url: https://www.gov.br/anp/pt-br/canais_atendimento/imprensa/noticias-comunicados
    active: true
  anpd:
    url: https://www.gov.br/anpd/pt-br/assuntos/noticias
    active: true
  ans:
    url: https://www.gov.br/ans/pt-br/assuntos/noticias
    active: true
  antaq:
    url: https://www.gov.br/antaq/pt-br/noticias
    active: true
  antt:
    url: https://www.gov.br/antt/pt-br/assuntos/ultimas-noticias
    active: true
  anvisa:
    url: https://www.gov.br/anvisa/pt-br/assuntos/noticias-anvisa
    active: true
  arquivonacional:
    url: https://www.gov.br/arquivonacional/pt-br/canais_atendimento/imprensa/copy_of_noticias
    active: true
  bn:
    url: https://www.gov.br/bn/pt-br/central-de-conteudos/noticias
    active: true
  cade:
    url: https://www.gov.br/cade/pt-br/assuntos/noticias
    active: true
  capes:
    url: https://www.gov.br/capes/pt-br/assuntos/noticias
    active: true
  casacivil:
    url: https://www.gov.br/casacivil/pt-br/assuntos/noticias
    active: true
  casaruibarbosa:
    url: https://www.gov.br/casaruibarbosa/pt-br/centrais-de-conteudo/noticias/2025
    active: true
  caslode:
    url: https://www.gov.br/caslode/pt-br/noticias
    active: true
  cbpf:
    url: https://www.gov.br/cbpf/pt-br/assuntos/noticias
    active: true
  cbtu:
    url: https://www.gov.br/cbtu/pt-br/assuntos/noticias
    active: true
  cdtn:
    url: https://www.gov.br/cdtn/pt-br/centrais-de-conteudo/noticias
    active: true
  cemaden:
    url: https://www.gov.br/cemaden/pt-br/assuntos/noticias-cemaden/ultimas-noticias
    active: true
  censipam:
    url: https://www.gov.br/censipam/pt-br/central-de-conteudos/noticias
    active: true
  cetem:
    url: https://www.gov.br/cetem/pt-br/noticias
    active: true
  cetene:
    url: https://www.gov.br/cetene/pt-br/assuntos/noticias
    active: true
  cgu:
    url: https://www.gov.br/cgu/pt-br/assuntos/noticias/ultimas-noticias
    active: true
  cidades:
    url: https://www.gov.br/cidades/pt-br/assuntos/noticias-1
    active: true
  cisc:
    url: https://www.gov.br/pt-br/noticias
    active: false
    disabled_reason: "URL generica, nao especifica da agencia"
    disabled_date: "2025-01-15"
  cnen:
    url: https://www.gov.br/cnen/pt-br/assunto/ultimas-noticias
    active: true
  cnpq:
    url: https://www.gov.br/cnpq/pt-br/assuntos/noticias
    active: true
  coaf:
    url: https://www.gov.br/coaf/pt-br/assuntos/noticias/ultimas-noticias
    active: true
  compras:
    url: https://www.gov.br/compras/pt-br/acesso-a-informacao/noticias
    active: true
  conarq:
    url: https://www.gov.br/conarq/pt-br/assuntos/noticias
    active: true
  conitec:
    url: https://www.gov.br/conitec/pt-br/assuntos/noticias
    active: true
  conselho-nacional-de-saude:
    url: https://www.gov.br/conselho-nacional-de-saude/pt-br/assuntos/noticias
    active: true
  corregedorias:
    url: https://www.gov.br/corregedorias/pt-br/aconteceu-aqui/noticias
    active: true
  crcnne:
    url: https://www.gov.br/crcnne/pt-br/assuntos/noticias
    active: true
  ctav:
    url: https://www.gov.br/ctav/pt-br/noticias
    active: true
  cti:
    url: https://www.gov.br/cti/pt-br/assuntos/noticias
    active: true
  ctir:
    url: https://www.gov.br/ctir/pt-br/assuntos/noticias/2025
    active: true
  cultura:
    url: https://www.gov.br/cultura/pt-br/assuntos/noticias
    active: true
  culturaviva:
    url: https://www.gov.br/culturaviva/pt-br/acesso-a-informacao/noticias
    active: true
  cvm:
    url: https://www.gov.br/cvm/pt-br/assuntos/noticias
    active: true
  defesa:
    url: https://www.gov.br/defesa/pt-br/centrais-de-conteudo/noticias
    active: true
  dnit:
    url: https://www.gov.br/dnit/pt-br/assuntos/noticias/
    active: true
  dnocs:
    url: https://www.gov.br/dnocs/pt-br/assuntos/noticias
    active: true
  ebserh:
    url: https://www.gov.br/ebserh/pt-br/comunicacao/noticias
    active: true
  empresas-e-negocios:
    url: https://www.gov.br/empresas-e-negocios/pt-br/empreendedor/mais-noticias
    active: true
  esd:
    url: https://www.gov.br/esd/pt-br/central-de-conteudo/noticias
    active: true
  esg:
    url: https://www.gov.br/esg/pt-br/centrais-de-conteudo/noticias
    active: true
  esocial:
    url: https://www.gov.br/esocial/pt-br/noticias
    active: true
  esporte:
    url: https://www.gov.br/esporte/pt-br/noticias-e-conteudos/esporte
    active: true
  fazenda:
    url: https://www.gov.br/fazenda/pt-br/assuntos/noticias
    active: true
  florestal:
    url: https://www.gov.br/florestal/pt-br/assuntos/noticias
    active: true
  fnde:
    url: https://www.gov.br/fnde/pt-br/assuntos/noticias
    active: true
  funag:
    url: https://www.gov.br/funag/pt-br/centrais-de-conteudo/noticias
    active: true
  funai:
    url: https://www.gov.br/funai/pt-br/assuntos/noticias/2025
    active: true
  funarte:
    url: https://www.gov.br/funarte/pt-br/assuntos/noticias/todas-noticias
    active: true
  fundacentro:
    url: https://www.gov.br/fundacentro/pt-br/comunicacao/noticias/noticias/ultimas-noticias
    active: true
  fundaj:
    url: https://www.gov.br/fundaj/pt-br/centrais-de-conteudo/noticias-1
    active: true
  gestao:
    url: https://www.gov.br/gestao/pt-br/assuntos/noticias/noticias
    active: true
  governodigital:
    url: https://www.gov.br/governodigital/pt-br/noticias
    active: true
  gsi:
    url: https://www.gov.br/gsi/pt-br/centrais-de-conteudo/noticias/2025
    active: true
  hfa:
    url: https://www.gov.br/hfa/pt-br/noticias?b_start:int=0
    active: true
  ibama:
    url: https://www.gov.br/ibama/pt-br/assuntos/noticias/2025
    active: true
  ibc:
    url: https://www.gov.br/ibc/pt-br/assuntos/noticias
    active: true
  ibde:
    url: https://www.gov.br/ibde/pt-br/assuntos/noticias
    active: false
    disabled_date: "2025-01-15"
  ibict:
    url: https://www.gov.br/ibict/pt-br/colecoes/colecao-de-todas-as-noticias-do-site
    active: true
  icmbio:
    url: https://www.gov.br/icmbio/pt-br/assuntos/noticias/ultimas-noticias
    active: true
  iec:
    url: https://www.gov.br/iec/pt-br/assuntos/noticias
    active: true
  ien:
    url: https://www.gov.br/ien/pt-br/assuntos/noticias
    active: true
  igualdaderacial:
    url: https://www.gov.br/igualdaderacial/pt-br/assuntos/copy2_of_noticias
    active: true
  imprensanacional:
    url: https://www.gov.br/imprensanacional/pt-br/assuntos/noticias
    active: true
  inca:
    url: https://www.gov.br/inca/pt-br/assuntos/noticias
    active: true
  incra:
    url: https://www.gov.br/incra/pt-br/assuntos/noticias
    active: true
  inep:
    url: https://www.gov.br/inep/pt-br/assuntos/noticias
    active: true
  ines:
    url: https://www.gov.br/ines/pt-br/central-de-conteudos/noticias
    active: true
  inma:
    url: https://www.gov.br/inma/pt-br/assuntos/noticias
    active: true
  inmetro:
    url: https://www.gov.br/inmetro/pt-br/centrais-de-conteudo/noticias
    active: true
  inpa:
    url: https://www.gov.br/inpa/pt-br/assuntos/noticias
    active: true
  inpe:
    url: https://www.gov.br/inpe/pt-br/assuntos/ultimas-noticias
    active: true
  inpi:
    url: https://www.gov.br/inpi/pt-br/central-de-conteudo/noticias
    active: true
  inpp:
    url: https://www.gov.br/inpp/pt-br/noticias
    active: true
  insa:
    url: https://www.gov.br/insa/pt-br/assuntos/noticias
    active: true
  inss:
    url: https://www.gov.br/inss/pt-br/noticias/ultimas-noticias
    active: true
  int:
    url: https://www.gov.br/int/pt-br/assuntos/noticias
    active: true
  investidor:
    url: https://www.gov.br/pt-br/noticias
    active: false
    disabled_reason: "URL generica"
    disabled_date: "2025-01-15"
  iphan:
    url: https://www.gov.br/iphan/pt-br/assuntos/noticias
    active: true
  ird:
    url: https://www.gov.br/ird/pt-br/assuntos/noticias
    active: true
  iti:
    url: https://www.gov.br/iti/pt-br/assuntos/noticias/indice-de-noticias/
    active: true
  jbrj:
    url: https://www.gov.br/jbrj/pt-br/assuntos/noticias
    active: true
  lapoc:
    url: https://www.gov.br/lapoc/pt-br/assuntos/noticias
    active: true
  lna:
    url: https://www.gov.br/lna/pt-br/assuntos/noticias
    active: true
  lncc:
    url: https://www.gov.br/lncc/pt-br/assuntos/noticias/ultimas-noticias-1
    active: true
  mast:
    url: https://www.gov.br/mast/pt-br/assuntos/noticias
    active: true
  mcom:
    url: https://www.gov.br/mcom/pt-br/noticias
    active: true
  mcti:
    url: https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/noticias/ultimas-noticias
    active: true
  mda:
    url: https://www.gov.br/mda/pt-br/noticias
    active: true
  mdh:
    url: https://www.gov.br/mdh/pt-br/assuntos/noticias
    active: true
  mdic:
    url: https://www.gov.br/mdic/pt-br/assuntos/noticias
    active: true
  mdr:
    url: https://www.gov.br/mdr/pt-br/noticias
    active: true
  mds:
    url: https://www.gov.br/mds/pt-br/noticias-e-conteudos/desenvolvimento-social/noticias-desenvolvimento-social
    active: true
  mec:
    url: https://www.gov.br/mec/pt-br/assuntos/noticias
    active: true
  memoriasreveladas:
    url: https://www.gov.br/memoriasreveladas/pt-br/centrais-de-conteudo/destaques
    active: true
  memp:
    url: https://www.gov.br/memp/pt-br/assuntos/noticias
    active: true
  mj:
    url: https://www.gov.br/mj/pt-br/assuntos/noticias
    active: true
  mma:
    url: https://www.gov.br/mma/pt-br/assuntos/noticias/ultimas-noticias
    active: true
  mme:
    url: https://www.gov.br/mme/pt-br/assuntos/noticias
    active: true
  mpa:
    url: https://www.gov.br/mpa/pt-br/assuntos/noticias
    active: true
  mre:
    url: https://www.gov.br/mre/pt-br/assuntos/portal-consular/alertas%20e%20noticias/noticias
    active: true
  mulheres:
    url: https://www.gov.br/mulheres/pt-br/central-de-conteudos/noticias
    active: true
  museudoindio:
    url: https://www.gov.br/museudoindio/pt-br/assuntos/noticias
    active: true
  museugoeldi:
    url: https://www.gov.br/museugoeldi/pt-br/arquivos/noticias
    active: true
  museus:
    url: https://www.gov.br/museus/pt-br/assuntos/noticias
    active: true
  nfse:
    url: https://www.gov.br/nfse/pt-br/noticias
    active: true
  observatorio:
    url: https://www.gov.br/observatorio/pt-br/assuntos/noticias
    active: true
  ouvidorias:
    url: https://www.gov.br/ouvidorias/pt-br/assuntos/noticias
    active: true
  palmares:
    url: https://www.gov.br/palmares/pt-br/assuntos/noticias
    active: true
  patrimonio:
    url: https://www.gov.br/patrimonio/pt-br/central-de-conteudo/noticias
    active: true
  pf:
    url: https://www.gov.br/pf/pt-br/assuntos/noticias/noticias-destaque
    active: true
  pgfn:
    url: https://www.gov.br/pgfn/pt-br/assuntos/noticias
    active: true
  planalto:
    url: https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/noticias
    active: true
  planejamento:
    url: https://www.gov.br/planejamento/pt-br/assuntos/noticias
    active: true
  pncp:
    url: https://www.gov.br/pncp/pt-br/central-de-conteudo/noticias
    active: true
  portos-e-aeroportos:
    url: https://www.gov.br/portos-e-aeroportos/pt-br/assuntos/noticias
    active: true
  povosindigenas:
    url: https://www.gov.br/povosindigenas/pt-br/assuntos/noticias
    active: false
    disabled_date: "2025-01-15"
  previc:
    url: https://www.gov.br/previc/pt-br/noticias
    active: true
  previdencia:
    url: https://www.gov.br/previdencia/pt-br/noticias
    active: true
  prf:
    url: https://www.gov.br/prf/pt-br/noticias/nacionais
    active: true
  produtividade-e-comercio-exterior:
    url: https://www.gov.br/pt-br/noticias
    active: false
    disabled_reason: "URL generica"
    disabled_date: "2025-01-15"
  propriedade-intelectual:
    url: https://www.gov.br/propriedade-intelectual/pt-br/assuntos/noticias
    active: true
  receitafederal:
    url: https://www.gov.br/receitafederal/pt-br/assuntos/noticias
    active: true
  reconstrucaors:
    url: https://www.gov.br/reconstrucaors/pt-br/acompanhe-a-reconstrucao/noticias
    active: true
  saude:
    url: https://www.gov.br/saude/pt-br/assuntos/noticias
    active: true
  secom:
    url: https://www.gov.br/secom/pt-br/assuntos/noticias
    active: true
  secretariageral:
    url: https://www.gov.br/secretariageral/pt-br/noticias
    active: true
  semanaenef:
    url: https://www.gov.br/semanaenef/pt-br/noticias
    active: true
  senappen:
    url: https://www.gov.br/senappen/pt-br/assuntos/noticias
    active: true
  servicoscompartilhados:
    url: https://www.gov.br/servicoscompartilhados/pt-br/acesso-a-informacao/noticias
    active: true
  servidor:
    url: https://www.gov.br/servidor/pt-br/assuntos/noticias
    active: true
  siscomex:
    url: https://www.gov.br/siscomex/pt-br/noticias
    active: false
    disabled_date: "2025-01-15"
  sri:
    url: https://www.gov.br/sri/pt-br/noticias/mais-noticias/ultimas-noticias
    active: true
  sudam:
    url: https://www.gov.br/sudam/pt-br/noticias-1
    active: true
  sudeco:
    url: https://www.gov.br/sudeco/pt-br/assuntos/noticias
    active: true
  sudene:
    url: https://www.gov.br/sudene/pt-br/assuntos/noticias
    active: true
  suframa:
    url: https://www.gov.br/suframa/pt-br/assuntos/noticias
    active: true
  susep:
    url: https://www.gov.br/susep/pt-br/central-de-conteudos/noticias
    active: true
  tesouronacional:
    url: https://www.gov.br/tesouronacional/pt-br/noticias
    active: true
  trabalho-e-emprego:
    url: https://www.gov.br/trabalho-e-emprego/pt-br/noticias-e-conteudo
    active: true
  transferegov:
    url: https://www.gov.br/transferegov/pt-br/noticias/noticias/2025
    active: true
  transportes:
    url: https://www.gov.br/transportes/pt-br/assuntos/noticias
    active: true
  turismo:
    url: https://www.gov.br/turismo/pt-br/assuntos/noticias
    active: true
